image: node:11-alpine

pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - npm i -g --unsafe-perm gridsome
  - gridsome build
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master
