/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Award: typeof import('./src/components/Award.vue')['default']
    HeaderToy: typeof import('./src/components/HeaderToy.vue')['default']
    JobWall: typeof import('./src/components/JobWall.vue')['default']
    Metaplay: typeof import('./src/components/Metaplay.vue')['default']
    Multipotentiality: typeof import('./src/components/Multipotentiality.vue')['default']
    Photography: typeof import('./src/components/Photography.vue')['default']
    SeriousBusiness: typeof import('./src/components/SeriousBusiness.vue')['default']
  }
}
